# This is a template yaml config file for federated training.
general:
  seed: [666, 888, 999, 111, 6666]
  save_local_model: false
  check_step: 200  # 不保存，因为现在使用pkl直接保存server类
  device: 'cuda'
  device_id: '2'

  eval_gap: 1
  local_learning_rate: 0.01
  learning_rate_decay: true
  learning_rate_decay_gamma: 0.99
  times: 1    # 重复实验次数
  dp: false   # 差分隐私
  dp_sigma: 0
  save_path: 'models'
  default_path: '/data2/cjq_data/experiments'
  search: true # 是否搜索遍历执行Baseline
  prev: 0


train:
  local_epochs: 5
  global_rounds: 100
  device_id: 0
  goal: 'bench_cifar100_dir0.1_nc100'
  batch_size: 50
  dataset_name: 'Cifar100_NonIID_Dir0.1_Client100'
  num_classes: 100
  num_clients: 100

  model: 'cnn'
  model_str: 'cnn'
  algorithm: 'All'
  all_algo: ['FedAvg', 'FedProx', 'SCAFFOLD', 'FedDyn', 'FedNTD', 'Ditto', 'FedRep', 'FedRoD', 'FedPAC', 'GPFL', 'DBE', 'FedAS']
  algorithm_list: ['FedPAC']

  participation_mode: 'cyclic'
  cyclic:
      T: 10
  participation_ratio: 0.5


attack:
  model_poison: false
  flag: false
  ratio: 0
  name: 'flip'
  round: -1   # 指定攻击发动的轮次。-1代表每次都发动攻击。
  algorithm_param:
    MPAF:
      fake_frac: 0
    STAT_OPT:
      compromise_ratio: 0
defense:
  flag: false
  name: 'krum'


algo_hyperparam:
  # GFL

  FedProx:
    mu:
      value: 0.001    # [0.001, 0.01, 0.1] 已经搜索过最佳值
  SCAFFOLD:
    server_learning_rate:
      value: 1  # No need for searching
  FedDyn:
    alpha:
      value: 0.1 # 已搜索出的最佳值
  MOON:
    tau:
      value: 0.5 # Default in its paper
    mu:
      value: 1
      search: [0.01, 0.1, 1, 10]
  FedNTD:
    tau:
      value: 1  # No need for search
    beta:
      value: 1 # No need for search
  # PFL
  Ditto:
    lamda:
      value: 1 # 已搜索出的最佳值
    plocal_steps:
      value: 1
  FedRep:
    plocal_steps:
      value: 1
  FedRoD:
    param:
      value: 'no'
  FedPAC:
    lamda:
      value: 1  # No need for search
  GPFL:
    GCE: 0
    CoV: 0
    # GPFL's hyper_parameter is defined within clientGPFL class.
    lamda:
      cnn: 0.01
      resnet: 0.0001
      vit: 0.0001
    mu:
      cnn: 0.1
      resnet: 0
      vit: 0
  DBE:
    kappa:
      cnn: 50
      resnet: 1
      vit: 1
    mu:
      cnn: 1
      resnet: 0.1
      vit: 0.1
  FedAS:
    param:
      value: 'no'












